# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/constraints.xdc

# Block Designs: bd/MainSesign/MainSesign.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==MainSesign || ORIG_REF_NAME==MainSesign} -quiet] -quiet

# IP: bd/MainSesign/ip/MainSesign_BasicLedController_0_0/MainSesign_BasicLedController_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==MainSesign_BasicLedController_0_0 || ORIG_REF_NAME==MainSesign_BasicLedController_0_0} -quiet] -quiet

# XDC: c:/Users/vince/Documents/xilinx/pynq-z2-rtl_blink/pynq-z2-rtl_blink.gen/sources_1/bd/MainSesign/MainSesign_ooc.xdc
